# Build stage:
FROM python:3.10.4 as build-container

COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

#Actual stage:
FROM python:3.10.4-slim-buster
COPY --from=build-container /usr/local/lib/python3.10/site-packages/ /usr/local/lib/python3.10/site-packages
COPY --from=build-container /usr/local/bin/uvicorn/ /usr/local/bin/uvicorn/

RUN useradd importuser
USER importuser

ADD config.py  /ip_reputation/config.py
ADD model  /ip_reputation/model
WORKDIR /ip_reputation

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

CMD ["python", "ip_reputation/model/importer.py", ]