version: '3.2'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ip-reputation-api
    environment:
        - PYTHONPATH=/ip_reputation/
        - TZ=Europe/London
        - APP_DEBUG=True
        - ENV=development
    command: uvicorn main:api --host 0.0.0.0 --port 8000 --reload
    volumes:
            - ./config.py:/ip_reputation/config.py
            - ./main.py:/ip_reputation/main.py
            - ./v1:/ip_reputation/v1
            - ./model:/ip_reputation/model
    ports:
            - 8000:8000
  redis:
    image: "redislabs/redisearch:latest"
    command: redis-server
    container_name: redis
    ports:
            - 6379:6379
    environment:
     - REDIS_REPLICATION_MODE=master
  importer:
    build:
      context: ./
      dockerfile: ./Dockerfile-importer
    image: "python:3.10.4"
    command: python /ip_reputation/model/importer.py
    environment:
     - PYTHONPATH=/ip_reputation/